import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./provider/ThemeProvider";
import ReactQueryProvider from "./provider/ReactQueryProvider";
import { Inter } from "next/font/google";

export const inter = Inter({subsets: ["latin"]}) 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
      <ReactQueryProvider>
      <ThemeProvider>{children}</ThemeProvider>
      </ReactQueryProvider>
      </body>
    </html>
  );
}
