version: "3.8"
services:
  userdb:
    image: postgres:9.6
    container_name: userdb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users
    ports:
      - "5432:5432"  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build: .
    ports:
      - "6000:6000" 
    environment:
      DATABASE_URL: postgresql://postgres:postgres@userdb:5432/users
      USER_ACCESS_SECRET: "ankush"
      
    depends_on:
      userdb:
        condition: service_healthy
    
    command: >
      sh -c "npx prisma migrate deploy && npm run dev"  # Apply migrations before running the app

